language: python
sudo: false
cache: bundler

python:
  - pypy

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7
    
install:
  - pip install cffi
  - pip install pytest

script:
  - make tests